<h1>Nuevo Actor</h1>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
</head>
<?php View::content();?>

<form method="post">
    <div class="row">
        <div class="col-4">
            <label class="form-label">Nombre</label>
            <input type="text" name="actor[first_name]" class="form-control">
        </div>
        <div class="col-4">
            <label class="form-label">Apellido</label>
            <input type="text" name="actor[last_name]" class="form-control">
        </div>
        <div class="col-4">
            <label class="form-label">Edad</label>
            <input type="text" name="actor[edad]" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Descripcion</label>
        <textarea type="text" name="actor[descripcion]" class="form-control" required></textarea>
        </div>
    <a href="/kumbiaphp/actor" class="btn btn-danger">Cancelar</a>
    
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('.js-example-basic-single').select2();
    });
</script>